version: '2'
services:
    reactjs:
        build: reactjs/.
        command: serve -s ./build/. -p 80
        #depends_on: 
        #    - loopback
        #ports:
        #    - "8001:80"
        volumes:
            - ./reactjs/:/reactjs
            - /reactjs/node_modules
        restart: always
        mem_limit: 64m
        networks:
            - nginx_default

    node:
        build: node/.
        command: npm start
        #depends_on: 
        mem_limit: 64m
        volumes:
            - ./node/:/node
            - ./node/node_modules:/node/node_modules
        restart: always
        networks:
            - nginx_default


networks:
    nginx_default:
        external: true
